// Deterministic JSON: keys sorted, 1-space indent. Same input must produce
// byte-identical output so `npm run data` diffs cleanly in review.

function sortKeys(value) {
  if (Array.isArray(value)) return value.map(sortKeys);
  if (value === null || typeof value !== 'object') return value;
  const sorted = {};
  for (const key of Object.keys(value).sort()) sorted[key] = sortKeys(value[key]);
  return sorted;
}

export function serializeDataFile(data, generatorPath) {
  const banner = [
    '// GENERATED by ' + generatorPath + ' — do not edit; run npm run data',
    '//',
    '// One global, one assignment. Loaded as a classic script before ccg-dashboard.js.',
  ].join('\n');
  return banner + '\nwindow.CCG_DATA = ' + JSON.stringify(sortKeys(data), null, 1) + ';\n';
}
